// Code generated by `caf gen telemetry`. DO NOT EDIT.
//
// the suite for the file beside it: one test per rule core states about
// what a cafaye signal may carry, and one per switch that turns
// telemetry off.
//
// WHAT IS DERIVED AND WHAT IS NOT, because a generated file that does not say
// which half of it is an instruction from core is an instruction from whoever
// last touched the generator.
//
// Derived, read out of the cafaye core telemetry contract vendored at
// cafaye/internal/contract/schemas/telemetry/ and pinned there by sha256:
// the three per-signal attribute allowlists and their value vocabularies, the
// names core refuses as a measurement attribute, the resource attributes, the
// error.type vocabulary, the span-name grammar, the OTEL_SDK_DISABLED switch, the three per-signal switches, and the four negative
// properties of the no-op path.
//
// From the manifest: the service name ("courier") and the language, which is what decided that
// Go was the right file to write.
//
// Written down here, and not derived from anything, because core's schemas
// constrain the shape of these values and do not state them: the namespace
// every cafaye service groups under ("cafaye"), and the address of the
// collector that ships with the local stack ("http://otel-collector:4317"). core's docs/observability.md and its
// examples/valid/telemetry/otel-endpoint.json agree on both; they are the
// fleet's documented values, not this generator's invention.
//
// To change any of it, change cafaye.yml or change core, and run
// `caf gen telemetry -force` again. The test beside this file is
// the thing that notices you did not.

package telemetry

import (
	"strings"
	"testing"
)

// The canary, in the form core's redaction schema asks for: a name that would
// carry content is refused by the allowlist check itself, and this is what proves
// the refusal bites. Asserted against the NAME SET rather than against a
// rendered payload because a setup that only has name sets has nothing else to
// render — and because a name-set assertion cannot be made to pass by
// truncation, which is the failure core's own note about asserting the two halves
// separately is about.
func TestNoAllowlistedAttributeNameNamesContent(t *testing.T) {
	for _, signal := range Signals() {
		t.Run(signal, func(t *testing.T) {
			// The ALLOWLIST, not Allowed(). Walking the order list instead is the
			// bug this comment is here about: an attribute added to the map and not
			// to the order list is invisible to a canary that reads the order
			// list, so muse.prompt would have been added on a signal with the
			// guard looking on. It was caught by adding muse.prompt to the traces
			// allowlist and watching this test pass, which is the only way it
			// could have been caught.
			//
			// Map order is random, and that is fine here: every failure names its
			// own signal and its own attribute, so the order failures arrive in
			// carries no information anybody needs.
			for name := range allowlists[signal] {
				if word, found := NamesContent(name); found {
					t.Errorf("%s carries %q on the %s signal, and core's redaction boundary refuses an "+
						"allowlisted name containing %q. The name has to be a fact about how a call was served",
						name, word, signal, word)
				}
			}
		})
	}
}

// The canary above reads the allowlist map and the public Allowed() reads the
// order list, so the two have to be the same set or one of them describes
// something the other does not contain.
//
// This is the invariant that makes the canary trustworthy, and it is asserted on
// its own rather than left as a comment because the failure it catches is a test
// that PASSES. An attribute in the map and not in the order list is invisible to
// anything reading Allowed(); an attribute in the order list and not in the map is
// a name Lookup refuses, so Allowed() advertises a name the setup will not accept.
// Neither is caught by the canary alone, which is exactly why the canary could
// pass while carrying a name that names content.
func TestTheAllowlistAndItsOrderListAreTheSameSet(t *testing.T) {
	for _, signal := range Signals() {
		t.Run(signal, func(t *testing.T) {
			listed := allowlists[signal]
			ordered := allowlistOrder[signal]
			if len(listed) == 0 {
				t.Fatal("the allowlist is empty")
			}
			if len(listed) != len(ordered) {
				t.Errorf("%s has %d allowlisted attribute(s) and %d ordered name(s), so one of the two is "+
					"describing something the other does not contain", signal, len(listed), len(ordered))
			}
			for name := range listed {
				if !contains(ordered, name) {
					t.Errorf("%q is allowlisted on %s but not in the order list, so Allowed() does not "+
						"report it and anything reading Allowed() cannot see it", name, signal)
				}
			}
			for _, name := range ordered {
				if _, found := listed[name]; !found {
					t.Errorf("%q is in %s's order list and not in its allowlist, so Allowed() advertises a "+
						"name Lookup refuses", name, signal)
				}
			}
		})
	}
}

// The prohibition, checked from both ends: core's refused names are on no
// signal's allowlist, and the two identities that have a legal home are on the
// resource.
//
// The first half is the whole mechanism. The second is what makes the first a
// refusal rather than a dead end — a prohibition with no destination is a
// prohibition a caller works around.
func TestProhibitedMeasurementsAreOnNoSignalAndTheirIdentifiersAreOnTheResource(t *testing.T) {
	prohibited := ProhibitedMeasurementAttributes()
	if len(prohibited) == 0 {
		t.Fatal("the prohibited measurement list is empty, so nothing is refused and this proves nothing")
	}

	for _, name := range prohibited {
		for _, signal := range Signals() {
			if _, allowed := Lookup(signal, name); allowed {
				t.Errorf("%q is one core refuses as a measurement attribute and it is on %s's allowlist. "+
					"A prohibited name that is also allowlisted is the failure the schema's not clause "+
					"exists to refuse, and it is reached by adding the name to the list rather than by "+
					"removing the prohibition", name, signal)
			}
		}
	}

	for _, name := range []string{"tenant_id", "account_id"} {
		if !OnResource(name) {
			t.Errorf("%q is refused on a measurement and is not on the resource, so the value has "+
				"nowhere legal to go", name)
		}
	}
}

// core's cardinality cap, restated as the thing a reader has to believe: the
// resource list is exempt from it and no signal allowlist is. That is why an
// identity belongs on one and not the other, and it is the only mechanism here
// that keeps a per-tenant total answerable after a stream folds.
//
// There is exactly one documented exception and it is checked as one rather than
// swept up in: core permits service.name on the LOG allowlist, because a log
// store that fans several services into one stream needs it as a label. It is on
// the logs allowlist and nowhere else, and it is bounded by the size of the
// fleet — so it is not a counterexample to the rule, it is the rule with a stated
// exception. A generated test that asserted "no resource name is on any
// allowlist" would be asserting something core's own schema does not say.
func TestIdentityIsOnTheResourceAndNoSignalAllowlistCarriesItButLogs(t *testing.T) {
	resource := ResourceAttributeNames()
	if len(resource) == 0 {
		t.Fatal("the resource attribute list is empty")
	}

	for _, name := range resource {
		for _, signal := range Signals() {
			_, allowed := Lookup(signal, name)
			permitted := allowed && name == "service.name" && signal == SignalLogs
			if allowed && !permitted {
				t.Errorf("%q is on the resource and on the %s allowlist. Resource attributes are "+
					"attached once per process; the same name on a measurement multiplies against every "+
					"other dimension", name, signal)
			}
		}
	}
	if _, allowed := Lookup(SignalTraces, "service.name"); allowed {
		t.Error("the traces signal allows service.name. core permits it on logs alone, and a span already " +
			"carries it on its resource")
	}
	if !OnResource("tenant_id") {
		t.Error("the resource does not carry tenant_id, which is the one identity core names in both places")
	}
}

// Metrics are coarser than traces on purpose, and this is the assertion that
// keeps a well-meaning symmetric edit from undoing that. The status CODE is a
// span attribute and the status CLASS is a metric attribute; a metric carrying
// the code is how a service reaches the cardinality cap in a week.
func TestMetricsAreCoarserThanTracesOnPurpose(t *testing.T) {
	if _, allowed := Lookup(SignalMetrics, "http.response.status_code"); allowed {
		t.Error("the metrics signal allows http.response.status_code. core carries the class on a " +
			"measurement and the code on a span; five hundred codes multiplied by every route is the cap")
	}
	if _, allowed := Lookup(SignalMetrics, "http.response.status_code_class"); !allowed {
		t.Error("the metrics signal does not allow http.response.status_code_class, so a measurement " +
			"has no bounded way to say what status a request got")
	}
	if _, allowed := Lookup(SignalTraces, "http.response.status_code"); !allowed {
		t.Error("the traces signal does not allow http.response.status_code, so a span cannot say what " +
			"status the response carried")
	}
}

// The no-op path, driven through every switch core names. core's schema does not
// accept the word "disabled"; it accepts a declaration of four things that do not
// happen, and this is the assertion that the four are what the code actually does.
func TestTheSwitchesTurnSignalsOff(t *testing.T) {
	for _, row := range []struct {
		name    string
		env     map[string]string
		enabled bool
		signals [3]bool
		reason  string
	}{
		{
			name:    "nothing set is on",
			enabled: true,
			signals: [3]bool{true, true, true},
		},
		{
			name:   "the spec's own switch turns everything off",
			env:    map[string]string{SwitchSDKDisabled: "true"},
			reason: SwitchSDKDisabled + "=true",
		},
		{
			name:   "and it is case-insensitive, because a person typed it",
			env:    map[string]string{SwitchSDKDisabled: "TRUE"},
			reason: SwitchSDKDisabled + "=true",
		},
		{
			name:    "traces off, the rest on",
			env:     map[string]string{SwitchTracesExporter: "none"},
			enabled: true,
			signals: [3]bool{false, true, true},
		},
		{
			name:    "metrics off, the rest on",
			env:     map[string]string{SwitchMetricsExporter: "none"},
			enabled: true,
			signals: [3]bool{true, false, true},
		},
		{
			name:    "logs off, the rest on",
			env:     map[string]string{SwitchLogsExporter: "none"},
			enabled: true,
			signals: [3]bool{true, true, false},
		},
		{
			name: "every exporter none is a no-op, and says so exactly once",
			env: map[string]string{
				SwitchTracesExporter:  "none",
				SwitchMetricsExporter: "none",
				SwitchLogsExporter:    "none",
			},
			reason: "every " + SwitchTracesExporter + ", " + SwitchMetricsExporter +
				" and " + SwitchLogsExporter + " is none",
		},
	} {
		t.Run(row.name, func(t *testing.T) {
			clearSwitches(t)
			for key, value := range row.env {
				t.Setenv(key, value)
			}

			if got := Enabled(); got != row.enabled {
				t.Errorf("Enabled() = %t, want %t", got, row.enabled)
			}
			for i, signal := range Signals() {
				if got := SignalEnabled(signal); got != row.signals[i] {
					t.Errorf("SignalEnabled(%q) = %t, want %t", signal, got, row.signals[i])
				}
			}
			if got := NoOpReason(); got != row.reason {
				t.Errorf("NoOpReason() = %q, want %q", got, row.reason)
			}
		})
	}
}

// clearSwitches unsets every switch this file knows about, so a row is decided by
// its own environment rather than by whatever the machine running it had set.
func clearSwitches(t *testing.T) {
	t.Helper()
	t.Setenv(SwitchSDKDisabled, "")
	for _, signal := range Signals() {
		t.Setenv(SwitchFor(signal), "")
	}
}

// The endpoint variable, and the precedence between the cafaye name and the
// standard OTel spelling. Written down rather than left to be discovered, because
// a contract with an undocumented precedence order is a bug report.
func TestEndpointPrefersTheCafayeName(t *testing.T) {
	for _, row := range []struct {
		name, cafaye, standard, want string
	}{
		{name: "nothing set is the shipped collector", want: DefaultEndpoint},
		{
			name:     "the cafaye variable wins",
			cafaye:   "http://otel.example:4317",
			standard: "http://ignored:4317",
			want:     "http://otel.example:4317",
		},
		{
			name:     "the standard spelling is honoured when the cafaye one is unset",
			standard: "http://generic:4317",
			want:     "http://generic:4317",
		},
	} {
		t.Run(row.name, func(t *testing.T) {
			t.Setenv(EndpointVariable, row.cafaye)
			t.Setenv("OTEL_EXPORTER_OTLP_ENDPOINT", row.standard)
			if got := Endpoint(); got != row.want {
				t.Errorf("Endpoint() = %q, want %q", got, row.want)
			}
		})
	}
}

// Low cardinality by construction. A segment that could hold an identifier is
// the whole failure this grammar prevents, so the test asserts it with a real
// identifier rather than with an ellipsis.
func TestASpanNameCannotHoldAnIdentifier(t *testing.T) {
	identifier := "usr_01J9Z8QK5M4N7P2R3T6V8W9X0A"

	if _, err := SpanName("user", identifier); err == nil {
		t.Errorf("a span name with a %d-character identifier segment was accepted. core caps a segment "+
			"at fifteen characters, which is what makes an id unspellable in one", len(identifier))
	}
	if _, err := SpanName("Request"); err == nil {
		t.Error("an operation with a capital letter was accepted. core's grammar is lowercase words, and a " +
			"segment that is not a lowercase word is a name nobody can group on")
	}
	if _, err := SpanName(""); err == nil {
		t.Error("a span name with no operation was accepted")
	}
	if _, err := SpanName("request", "route", "v1", "extra"); err == nil {
		t.Error("a span name with more segments than core's grammar allows was accepted")
	}

	name, err := SpanName("request")
	if err != nil {
		t.Fatalf("SpanName(\"request\") = %v, want the shortest legal name", err)
	}
	if name != ServiceName+".request" {
		t.Errorf("SpanName(\"request\") = %q, want %q. The service prefix is mandatory: an unprefixed "+
			"name says what happened and not who did it", name, ServiceName+".request")
	}
	if _, err := SpanName("provider_call", "provider"); err != nil {
		t.Errorf("SpanName(\"provider_call\", \"provider\") = %v, want a legal three-segment name", err)
	}
	// core's own worked example, spelled with this service's name. It is here
	// because it is the shape the grammar is for: service, operation, and a
	// target only where the operation alone would be ambiguous across the fleet.
	if got, err := SpanName("provider", "call"); err != nil || got != ServiceName+".provider.call" {
		t.Errorf("SpanName(\"provider\", \"call\") = %q, %v, want %q",
			got, err, ServiceName+".provider.call")
	}
}

// Default-deny, from the angle a caller meets it: a name nobody allowlisted, and
// a name that names content. Both refusals have to be loud, because a quiet
// refusal is a dashboard that silently stops having a dimension.
func TestTheDefaultIsDeny(t *testing.T) {
	for _, row := range []struct {
		name, signal, attribute string
	}{
		{name: "an undeclared name", signal: SignalTraces, attribute: "muse.prompt"},
		{name: "a content name on logs", signal: SignalLogs, attribute: "log.prompt"},
		{name: "a trace attribute on a metric", signal: SignalMetrics, attribute: "otel.status_code"},
		{name: "a metric dimension on a span", signal: SignalTraces, attribute: "http.response.status_code_class"},
		{name: "an identifier as a dimension", signal: SignalMetrics, attribute: "user_id"},
		{name: "a URL as a dimension", signal: SignalMetrics, attribute: "url.full"},
	} {
		t.Run(row.name, func(t *testing.T) {
			if err := Check(row.signal, row.attribute, "anything"); err == nil {
				t.Errorf("Check(%q, %q) accepted it. The default is deny, and %q is not on %s's list",
					row.signal, row.attribute, row.attribute, row.signal)
			}
		})
	}

	if err := Check(SignalTraces, "http.route", "/v1/users/{id}"); err != nil {
		t.Errorf("the route template was refused: %v. A template has one value per endpoint; a concrete "+
			"path has one per request, which is why url.path is on no list at all", err)
	}
}

// Value constraints, not just names. An allowlist that says which names are legal
// and nothing about their values is half the rule, and the half that lets
// `db.operation: "DROP TABLE users"` through.
func TestValuesAreConstrainedNotJustNames(t *testing.T) {
	for _, row := range []struct {
		name, signal, attribute, value string
	}{
		{name: "a database verb", signal: SignalTraces, attribute: "db.operation", value: "select"},
		{name: "a status code in range", signal: SignalTraces, attribute: "http.response.status_code", value: "503"},
		{name: "a status class", signal: SignalMetrics, attribute: "http.response.status_code_class", value: "5xx"},
		{name: "a severity", signal: SignalLogs, attribute: "log.severity", value: "error"},
	} {
		t.Run(row.name, func(t *testing.T) {
			if err := Check(row.signal, row.attribute, row.value); err != nil {
				t.Errorf("Check(%q, %q, %q) = %v, want it accepted",
					row.signal, row.attribute, row.value, err)
			}
		})
	}

	// The why column is the half of the assertion that matters: a refusal a
	// caller cannot act on is a refusal somebody disables, so each row checks
	// that the message names the reason rather than only that it is non-empty.
	// Each substring names a distinct refusal class, which is what the generated
	// code produces — "not one of core's N values" for a closed vocabulary,
	// "outside it" for a numeric bound, and so on — so a row cannot be made to
	// pass by a different row's message.
	for _, row := range []struct {
		name, signal, attribute, value, why string
	}{
		{
			name: "a database verb that is not one", signal: SignalTraces, attribute: "db.operation",
			value: "DROP TABLE users",
			why:   "not one of core's",
		},
		{
			name: "a status code out of range", signal: SignalTraces, attribute: "http.response.status_code",
			value: "999",
			why:   "outside it",
		},
		{
			name: "an integer attribute given a word", signal: SignalTraces, attribute: "http.response.status_code",
			value: "5xx",
			why:   "core declares this attribute an integer",
		},
		{
			name: "a severity that is not one", signal: SignalLogs, attribute: "log.severity",
			value: "critical",
			why:   "not one of core's",
		},
		{
			name: "a route with a query string", signal: SignalTraces, attribute: "http.route",
			value: "/v1/users/{id}?expand=all",
			why:   "does not match core's pattern",
		},
	} {
		t.Run(row.name, func(t *testing.T) {
			err := Check(row.signal, row.attribute, row.value)
			if err == nil {
				t.Fatalf("Check(%q, %q, %q) accepted it", row.signal, row.attribute, row.value)
			}
			if !strings.Contains(err.Error(), row.why) {
				t.Errorf("the refusal does not say why: %v", err)
			}
		})
	}
}

// The route template is bounded by a length cap rather than by a pattern that can
// tell a template from a concrete path — a concrete path matches the same
// pattern. So the bound is what keeps the cardinality finite, and this is the
// assertion that the bound exists.
func TestARouteIsBoundedEvenThoughItsPatternAcceptsAConcretePath(t *testing.T) {
	if err := Check(SignalTraces, "http.route", "/v1/users/{id}"); err != nil {
		t.Fatalf("the template was refused: %v", err)
	}

	if err := Check(SignalTraces, "http.route", "/"+strings.Repeat("a", 300)); err == nil {
		t.Error("a 300-character route was accepted. The pattern admits it and the length cap is what " +
			"refuses it, which is why the cap is the part that matters")
	}
}

// Every integer core allowlists is inside the range every language in this fleet
// can carry through JSON without losing precision.
//
// It cannot fire on today's contract and it is here anyway: JavaScript's number
// is a float64, so an integer above 2^53-1 crosses a JSON boundary silently
// wrong, and the first attribute that would do that is a refusal at the point of
// emission rather than a wrong number in a backend that cannot represent it.
func TestEveryAllowlistedIntegerStaysInsideTheSafeJSONRange(t *testing.T) {
	for _, signal := range Signals() {
		t.Run(signal, func(t *testing.T) {
			for _, name := range Allowed(signal) {
				attribute, _ := Lookup(signal, name)
				if attribute.Kind != KindInteger {
					continue
				}
				if attribute.Max > MaxSafeJSONInteger {
					t.Errorf("%q is bounded by %d, which is above 2^53-1 (%d). Every language in this "+
						"fleet that reads JSON as a float64 will lose this value",
						name, attribute.Max, MaxSafeJSONInteger)
				}
			}
		})
	}
}

// The identity this file was generated for, pinned. A regenerated file changes
// when the manifest or the contract changes, and a setup whose service name has
// drifted from its manifest has spans nobody can attribute.
func TestTheServiceIdentityMatchesTheManifest(t *testing.T) {
	if ServiceName != "courier" {
		t.Errorf("ServiceName = %q, want %q", ServiceName, "courier")
	}
	if EndpointVariable != "COURIER_OTEL_ENDPOINT" {
		t.Errorf("EndpointVariable = %q, want %q", EndpointVariable, "COURIER_OTEL_ENDPOINT")
	}
	if !strings.HasPrefix(EndpointVariable, strings.ToUpper(ServiceName)) {
		t.Errorf("EndpointVariable = %q, which does not start with the upper-cased service name, and the "+
			"upper-cased service name plus _OTEL_ENDPOINT is the only contract core names", EndpointVariable)
	}
	if Namespace != "cafaye" {
		t.Errorf("Namespace = %q, want %q", Namespace, "cafaye")
	}
}

// SwitchFor is the per-signal switch for a signal name. Exported from the
// package under test rather than private to this file, because a caller wiring
// the SDK needs it too and a second copy is a second place to forget.
func SwitchFor(signal string) string {
	switch signal {
	case SignalTraces:
		return SwitchTracesExporter
	case SignalMetrics:
		return SwitchMetricsExporter
	case SignalLogs:
		return SwitchLogsExporter
	}
	return ""
}
